### ISSUE TITLE
feature suggestion: self grant permissions if adb over tcp is already enabled on device

### ISSUE THREAD

**Issue by mailinglists35** [zacharee/Tweaker#11]
when I first start the app it shows me two choices: root or computer.

I don't have root, but I already have adb enabled on device in tcpip mode

please allow a third choice where the app connects directly to localhost via adb and gives itself the permissions
thanks

**Comment by zacharee** [comment]
You can do this with the beta version if you have Shizuku installed.

**Comment by mailinglists35** [comment]
well shizuku would be a fourth option, then :)

**Comment by zacharee** [comment]
If you already have your own local ADB server set up, then you should have no issue running the command to grant the permissions from Termux or something. I don't think it really makes sense to add automatic functionality when Shizuku already exists and is what most people would use.
