### ISSUE TITLE
Cannot hide VPN Icon "key" in Status Bar

### ISSUE THREAD

**Issue by TheThunderspy** [zacharee/Tweaker#13]
Switching VPN Icon does not work on my device

Android 7.0 sdk 24
Do I have to introduce or do something else to fix this..?

![Screenshot_20210308-112301 1](https://user-images.githubusercontent.com/78750328/110349587-d5c8e400-8000-11eb-8c9d-3feaf42249b6.png)

**Comment by zacharee** [comment]
Take a look at the terms, specifically, this section:

> Some things simply will not function on your device! If certain status bar icon toggles have no effect, or Demo Mode does not function, there is absolutely nothing I can do.

https://github.com/zacharee/Tweaker/blob/master/app/src/main/assets/terms.md#limitations
