### ISSUE TITLE
Hide alarm on Huawei doesn't work

### ISSUE THREAD

**Issue by auipga** [zacharee/Tweaker#4]
On my Huawei Mate 20 Pro running Android 10/EMUI 10.1.0 the alarm cannot be hidden using the `alarm` key (anymore).
```sh
settings put secure icon_blacklist alarm
```
I also tried `alarms` and  `clock` with no result.

If somebody knows the correct keyword, please let us know.
Thanks.

**Comment by Lechitam99** [comment]
> On my Huawei Mate 20 Pro running Android 10/EMUI 10.1.0 the alarm cannot be hidden using the `alarm` key (anymore).
> 
> ```shell
> settings put secure icon_blacklist alarm
> ```
> 
> I also tried `alarms` and `clock` with no result.
> 
> If somebody knows the correct keyword, please let us know.
> Thanks.

**Comment by vasek0001** [comment]
> On my Huawei Mate 20 Pro running Android 10/EMUI 10.1.0 the alarm cannot be hidden using the `alarm` key (anymore).
> 
> ```shell
> settings put secure icon_blacklist alarm
> ```
> 
> I also tried `alarms` and `clock` with no result.
> 
> If somebody knows the correct keyword, please let us know.
> Thanks.

Vasek
