### ISSUE TITLE
wont apply custom ui sounds on google pixel 6 pro

### ISSUE THREAD

**Issue by arfanvlk** [zacharee/Tweaker#42]
not sure if it is intended but on my pixel six pro if I change any of the sounds it won't apply and I don't know how to fix it.

i am running the latest version of android 12

**Comment by Owlius** [comment]
I have same issue, but I did also notice that the temporary sound file that the app creates don't have a file extension (.ogg)

**Comment by e-t-l** [comment]
I'm also experiencing this. Pixel 7 running GrapheneOS

**Comment by e-t-l** [comment]
@zacharee Any update about this? Selecting a file for Charging, for example, fails with the error, `Error creating file: Operation not permitted`. From googling this error, it looks like maybe SystemUI Tuner needs storage permissions?

**Comment by e-t-l** [comment]
Ok I don't know why SysUI Tuner can't do it, but from any normal ADB shell (or a different app that can set settings, like Macrodroid or Tasker), run:
`settings put global charging_started_sound /storage/emulated/0/path/to/sound/file.mp3`
