### ISSUE TITLE
Immersive Mode doesn't work at all

### ISSUE THREAD

**Issue by cyatarow** [zacharee/Tweaker#43]
None of the full screen, status bar, or nav bar modes worked.

SystemUI Tuner version: 342
Android version: 12 (June 2022)
Device: Pixel 4a 5G

**Comment by zacharee** [comment]
Please read the [Safety/Warnings section of the terms](https://github.com/zacharee/Tweaker/blob/master/app/src/main/assets/terms.md#safetywarnings).

**Comment by e-t-l** [comment]
@zacharee I'm a bit confused by the part about immersive mode in the terms you linked. If apps can no longer change immersive mode, how do full-screen apps like videos work?

**Comment by Apisit420** [comment]
This is good 👍
