### ISSUE TITLE
Remove Battery Charging Animation Without Turn Off All Other Animations. 

### ISSUE THREAD

**Issue by A-74** [zacharee/Tweaker#45]
When ever I plug my phone to the charger there is this **annoying battery animation** poping up!
![Screenshot_20220811-223108_One UI Home](https://user-images.githubusercontent.com/110195634/184192951-60d6a207-0fbc-462e-b051-2df115cf50dd.jpg)
Now I know system ui tuner can't remove nor change some manufacturer default settings but **there is a way to remove all android animations** using [Settings>Accessibility >Visibility Enhancements>Remove Animations (Under Colors and Clarity)] So i'm asking is there a way to **just remove battery charging animation without removing all other animations** using system ui tuner? (Please tell me if you know other ADB methods to do this without using root if system ui tuner can't do this) **Thank You!!!**

**Comment by zacharee** [comment]
You may be able to disable it with Samsung's LockStar app, but there are no settings you can apply through ADB that I can find.

**Comment by 1NT3RC3PTOR** [comment]
> When ever I plug my phone to the charger there is this **annoying battery animation** poping up!
> ![Screenshot_20220811-223108_One UI Home](https://user-images.githubusercontent.com/110195634/184192951-60d6a207-0fbc-462e-b051-2df115cf50dd.jpg)
> Now I know system ui tuner can't remove nor change some manufacturer default settings but **there is a way to remove all android animations** using [Settings>Accessibility >Visibility Enhancements>Remove Animations (Under Colors and Clarity)] So i'm asking is there a way to **just remove battery charging animation without removing all other animations** using system ui tuner? (Please tell me if you know other ADB methods to do this without using root if system ui tuner can't do this) **Thank You!!!**
