### ISSUE TITLE
Alarm icon in status bar still shows after being turned off. 

### ISSUE THREAD

**Issue by nwithers-ecr** [zacharee/Tweaker#46]
Android 13
Pixel 5a
Version 347 (updated 09/04)

I went through and disabled ever status bar icon. I'd prefer to see them in KLWP. 

As far as I can tell all the icons are correctly hidden now, except for the alarm. 

I thought it might be because it was created by bedtime mode in the clock app and not the normal way, but disabling that and making a normal alarm still caused the icon to show. 

Beyond that, it also has some left padding. (From other invisible icons maybe?)

![Screenshot_20220908-052552.png](https://user-images.githubusercontent.com/79856213/189086808-51b31c73-16ec-47ac-87a2-75ff960d251a.png)

**Comment by zacharee** [comment]
That looks like a notification icon. SystemUI Tuner can't hide those.

**Comment by nwithers-ecr** [comment]
Ok, thanks. I see the clock app has a few different toggles so I'll try to use those.
