### ISSUE TITLE
List of names/keys for icon blacklist

### ISSUE THREAD

**Issue by unalignedcoder** [zacharee/Tweaker#55]
While SystemUI does a great job blacklisting status bar icons from within its interface, when used as a Tasker plugin the user is required to know name and key of the icons they want to hide.

It would be very helpful if the app made these combinations transparent to the user.

For example, I'd like to automate via MacroDroid the hiding of the mobile/sim icons, but I need to know the name/key for this. SystemUI, of course, already "knows" this combination.

As a solution, the name/key values could be written in small characters under each item on the "blacklist icon" page.

**Comment by Rosdel00** [comment]
Off

**Comment by zacharee** [comment]
Keys are now listed in version 349.
