### ISSUE TITLE
[Question/Feature Request] Hide Signal Bar of Sim Card 2

### ISSUE THREAD

**Issue by o-data** [zacharee/Tweaker#59]
Recently discover this App, thank you.

Would like to ask if this is possible, I'm using a Dual Sim phone and the Signal Bar showing up Sim 1 and Sim 2, is it possible to just hide Sim 2 instead of hiding all?

Thank you.

**Comment by zacharee** [comment]
If your device groups both signal bar icons into one slot, there isn't anything SystemUI Tuner can do to hide only one.

**Comment by o-data** [comment]
Closing as it determine by the system/OS
