### ISSUE TITLE
Icon blacklist not persisted in 351

### ISSUE THREAD

**Issue by ZTenski** [zacharee/Tweaker#62]
In version 351 from fdroid Izzy, the icon blacklist is not persisted.

I uninstalled and reinstalled clean (both system ui tuner and quickstar) to verify that it's not some option that i've messed up, and to start from a clean slate.

Version 350 works fine, and I have downgraded to this version. I did not capture an adb log, but I can try if this behaviour doesn't repro. It only occurs on reboot though, and i'm not rooted so collecting the log may be a bit of a struggle. I enabled crash reports.

Details:
BEHAVIOUR
v350 behaviour: icon blacklist settings preserved on reboot.

v351 behaviour: icon blacklist not preserved on reboot. All settings reset in the icon blacklist and clock position menus when the phone is restarted. Icon blacklist remains in the persistent options menu, but since the options are all reset, the values I set are not applied.

APP STATE
App state, all other options as per default after reinstall of the app:
- fresh install of quickstar 6.3.06.31
- fresh reinstall for both versions. Same options applied for both versions.
- all permissions granted that were asked for, including those over adb via shizuku, constant notification, and display over apps
- in status bar settings, clock set to "right"
- in status bar icon blacklist, bluetooth, volume, alarm icons set to "off". In the bottom <auto> section, bluetooth_connected set to "off"
- in persistent options, icon blacklist set to "on"

PLATFORM STATE
- OS - Android 13, Jan 1 security patch
- OneUI 5.0
- Hardware - Samsung Galaxy s21 ultra 5g - SM-G998W
- Launcher - Action Launcher 50.5

**Comment by ZTenski** [comment]
Also, forgot to mention, I use the app AutoStart to ensure the service starts 20 seconds after I unlock the phone after a reboot. 

This works on v350 to reload the app, and all settings are applied as soon as Auto Start kicks it, but for v351, I can see it is started in the running apps drawer, but the settings are reverted as described above.

**Comment by zacharee** [comment]
Does this test version work as expected? https://github.com/zacharee/Tweaker/releases/tag/BLPT

**Comment by ZTenski** [comment]
This version works perfectly, thanks a lot. Should be able to close this, I'll pick up the next revision from FDroid Izzy when it comes :)

Just wanted to say, I appreciate your work on this app. Makes my status bar usable for more than 2 notifications, and disables a load of annoyances for me, you've probably saved me hours over the last few years from missed notifications and random popups. Thanks :)
