### ISSUE TITLE
My screen turned blank 

### ISSUE THREAD

**Issue by rahulh30** [zacharee/Tweaker#65]
My screen turned blank after I turned on dark mode. Please give me a solution.

**Comment by zacharee** [comment]
Check out the Troubleshooting section of the terms: https://github.com/zacharee/Tweaker/blob/master/app/src/main/assets/terms.md#safetywarnings.

**Comment by Mdhw27** [comment]
Bonsoir ici je ne pas besoin de tout ça je recherche simplement un solution sur mon portable setout bon courage à tout le monde est bonne continuation voilà ce que j'ai à dire au revoir  et  salut
