### ISSUE TITLE
[Feature request] Ability to switch language

### ISSUE THREAD

**Issue by SainoNamkho** [zacharee/Tweaker#75]
Hello zacharee. I'm from Chinese and my system language is simplified Chinese. I just can't understand most of the Chinese translations in this app. And I'm tired of the "open systemui tuner - don't know what it says - go to settings and set system language to English - wait for the system ui to reload in English - go back to systemui tuner and tweak something - set system language back to simplified Chinese" loop.

It will be great if I can directly use English in this app. Thanks a lot!

**Comment by Apisit420** [comment]
8b79c40

**Comment by zacharee** [comment]
The next version will allow you to change the language from Settings on Android 13 and later.
