### ISSUE TITLE
Settings keep reverting daily?

### ISSUE THREAD

**Issue by Lumattix** [zacharee/Tweaker#78]
Hi team,

I have under the Interface > Blacklist Icons > Auto keep having to turn off Cast/Screen Record options as these keep reverting back to ON basically daily.

This is really distracting for the video content I record for my lessons

Samsung Galaxy S23 Ultra

How can I stop the settings reverting?

**Comment by zacharee** [comment]
You can use the Persistent Options menu in the navigation drawer to force settings to stay on what you set them to.
