### ISSUE TITLE
Missing or invisible help text

### ISSUE THREAD

**Issue by xim** [zacharee/Tweaker#80]
Trying to use SystemUI tuner on an Android 13 tablet. The help screens are less than useful.

![Screenshot_20230721-233046](https://github.com/zacharee/Tweaker/assets/169057/80984860-cd12-4150-9c52-baac472b50e1)

![Screenshot_20230721-233146](https://github.com/zacharee/Tweaker/assets/169057/379bcb5d-64c6-48fd-a288-5ef1456b1862)

**Comment by Apisit420** [comment]
Ok new year and come Pesach
