### ISSUE TITLE
Add "Show Taps" feature

### ISSUE THREAD

**Issue by yozzyurubuza** [zacharee/Tweaker#86]
Can you add the feature "Show Taps" from Developer Options?
Thanks!

**Comment by Apisit420** [comment]
🧐👍

**Comment by Apisit420** [comment]
> Can you add the feature "Show Taps" from Developer Options? Thanks!

Conser

**Comment by zacharee** [comment]
This will be available in 361.

**Comment by yozzyurubuza** [comment]
Might be a little too late, but I just migrated to a new phone and glad to see that this is implemented now. Thanks a lot!
