### ISSUE TITLE
Wireless ADB

### ISSUE THREAD

**Issue by xhinixhi** [zacharee/Tweaker#87]
Can you add additional tweak to turn on wireless adb?

**Comment by Terkyz** [comment]
YES PLEASE! This is a must needed.

**Comment by Apisit420** [comment]
👍

**Comment by Apisit420** [comment]
For snoop dog 🍻

**Comment by zacharee** [comment]
This will be available in 361.

**Comment by lisaac** [comment]
In the permanent options, enabling wireless ADB will become ineffective if the Wi-Fi connection is completely disconnected (e.g., switching to cellular) and then reconnected to Wi-Fi. And in the developer options, the wireless ADB switch is turned on, but there is NO wireless ADB port displayed, and it is not possible to connect via ADB.

**Comment by lisaac** [comment]
Is it possible to auto trigger this option every time we connect to Wi-Fi.

**Comment by DrAnonym666** [comment]
> Can you add additional tweak to turn on wireless adb?

Sorry for late reply... 

You can usually use the "Quick tile settings for programmers"... There you can add easy more shortcuts into
