### ISSUE TITLE
Can't get past setup screen

### ISSUE THREAD

**Issue by cooolgamer** [zacharee/Tweaker#92]
What's happening is, I read the terms online because I just can't scroll to see them on the app, but it still says I didn't read them... But I can't scroll so I'm stuck and can't go further

**Comment by cooolgamer** [comment]
Fiund a workaround: just put auto rotate and you can scroll in landscape

**Comment by roadkell** [comment]
Same issue here, but I can't rotate an Android TV, neither do I have a touch or scroll wheel input.
Solved by connecting a mouse with scroll wheel. Yet, being able to get focus on the terms text would be handy.
