### ISSUE TITLE
Unable to hide Bluetooth icon in status bar

### ISSUE THREAD

**Issue by lumia1998** [zacharee/Tweaker#94]
![image](https://github.com/zacharee/Tweaker/assets/63107956/912df73b-1a98-4443-b165-56d169acf431)

My phone is a Vivo phone with Android 14.
Could this be why China modified Android?

**Comment by zacharee** [comment]
Vivo's Android skin is incredibly customized and is likely why the icon blacklist isn't working.

**Comment by lumia1998** [comment]
Yes I've tried multiple adb commands to hide the bluetooth icon and it doesn't work, maybe it needs to parse the system files in his firmware to solve the problem
Anyway thanks for the reply!
