### ISSUE TITLE
Samsung One UI 6 - Sim 2 (mobile2) hide not working 

### ISSUE THREAD

**Issue by shredinjohn** [zacharee/Tweaker#97]
I have tried disabling both phone signal 2 and mobile 2 .. but specific sim is not getting hidden. .. when I disable (mobile) under auto it's completely hides both the sim.. help me with the fix dev :)

**Comment by zacharee** [comment]
I can't fix this unfortunately. Both mobile icons are in the same slot on Samsung devices, so they can't be hidden individually.
